### ISSUE TITLE
Verificar Funcionamiento

### ISSUE THREAD

**Issue by fsr1410** [fsr1410/repo-STMY21#7]
Controlar el correcto acoplamiento de:

- [x] Controller
- [x] Service
- [x] Util

- [x] Encontrar Errores e informarlos.

**Comment by tatii0801** [comment]
Al verificar y controlar el Trabajo Práctico N°5 me di cuenta que hubo unos cuantos errores en el Controller y en el Service especialmente por la confusión de los nombres, ahora se puede decir que están correctamente y corregidos esos errores que anteriormente los informamos a través de los Commits. Así que se puede decir que el Trabajo Práctico N°5 funciona y obtenemos un resultado correcto
Es decir este trabajo está terminado!!!
